name: Footprint2
on:
  schedule:
    - cron: '0 2-5 * * 2-5'

jobs:
  timeline:
    name: add new date
    runs-on: ubuntu-latest
  
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: save the date
        run: |
          date >> timeline.log

      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: commit
        run: |
          # Stage the file, commit and push
          git add .
          git commit -m "mon to fri @ noon"
          git push origin main
  